language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t dlwnstj21/myapp -f ./front/Dockerfile.dev ./front

script:
  - docker run -e CI=true dlwnstj21/myapp npm test

after_success:
  - docker build -t dlwnstj21/docker-front ./front
  - docker build -t dlwnstj21/docker-back ./back
  - docker build -t dlwnstj21/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push dlwnstj21/docker-front
  - docker push dlwnstj21/docker-back
  - docker push dlwnstj21/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-myapp"
  env: "Dockermyapp-env"
  bucket_name: elasticbeanstalk-us-east-2-106683816905
  bucket_path: "docker-myapp"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY